---
- name: restart apache handler
  service: 
    name: apache2 
    state: restarted
    notify:
        - check port 80

# lets triger handler via handler
- name: check port 80
  wait_for: 
    state: started
    host: 'localhost'
    port: 80
    timeout: 15
    delay: 5
