---
# Execution:
# shell$ ansible-playbook playbooks/simple_playbook.yml

- hosts: all

  tasks:
   - name: "ping all"
     ping:

   - name: "execute a shell command"
     shell: "date; whoami; df -h;"

  roles: 
      - some_role
      - { role: another_role, some_variable: 'learnxiny', tags: ['my_tag'] }
  
  pre_tasks:
      - name: some pre-task
        shell: echo 'this task is the last, but would be executed before roles, and before tasks'
