---
# Execution:
# shell$ ansible-playbook playbooks/simple_playbook.yml
#
# NOTE that tasks would execute in order:
#   1) pre_tasks
#   2) roles 
#   3) tasks

- hosts: all

  tasks:
   - name: "ping all"
     ping:

   - name: "execute a shell command"
     shell: "date; whoami; df -h;"

  roles: 
      - some_role
      - { role: another_role, some_variable: 'learnxiny', tags: ['my_tag'] }
      - { role: simple_apache_role, some_variable: 'learnxiny', tags: ['apache2'] }
  
  pre_tasks:
      - name: some pre-task
        shell: echo 'this task is the last, but would be executed before roles, and before tasks'
