---
# Execution:
# shell$ ansible-playbook playbooks/simple_playbook.yml

- hosts: all

  tasks:
   - name: "ping all"
     ping:
     tags: 
       - some_tag
       - tagA
       - tag_other

   - name: "execute a shell command"
     shell: "date; whoami; df -h;"
     tags: ["tagA", "other tag"]
